spring.application.name=ProjectCNPM
spring.datasource.url=jdbc:mysql://localhost:3306/projectcnpm?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=020105
server.port=8081
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

cloudinary.url=${CLOUDINARY_URL:cloudinary://747129869863278:TdI1xrAIgu_fB9bbLQmhR2KmDCA@dfz0c8xcx}
cloudinary.folder=${CLOUDINARY_FOLDER:project-cnpm/products}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=van900379@gmail.com
spring.mail.password=skhd nmdl zoxg vtek
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=4968789751616645464897978789212313215646584651321864713216489415348769789516549876813213132486979786
jwt.expiration-ms=864000000
